### ISSUE TITLE
Quantify the uncertainties in t95() function

### ISSUE THREAD

**Issue by sandrinecharles** [aursiber/rbioacc#4]

**Comment by virgile-baudrot** [comment]
- We have to look at function "t95.R" and add the 95CI, and also havong all the distribution.
- It would be great to have a function where you ask for any X% "tX" and with the distribution and any quantiles.

**Comment by virgile-baudrot** [comment]
move to gitlab repository: https://gitlab.com/qonfluens/model/rbioacc/-/issues/3
