### ISSUE TITLE
Naming convention conflict with package {plotly}

### ISSUE THREAD

**Issue by milena-marchant** [aursiber/rbioacc#5]
PPC plots are not compatible with the {plotly} package anymore, as well as the `predictTK` plots when adding a `geom_vline` to symbolize end of accumulation phase. This can be observed in the MOSAIC bioacc application.
```r
library(rbioacc)
library(ggplot2)
library(plotly)

data("Male_Gammarus_Single")
modelData_MGS <- modelData(Male_Gammarus_Single, time_accumulation = 4)
fit_MGS <- fitTK(modelData_MGS, iter = 10000)
pl <- ppc(fit_MGS)
ggplotly(pl) # error

time4pred <- sort(c(seq(0, 12, length.out = 50), 4))
data_4pred <- data.frame(time = time4pred)
data_4pred$expw <- 7.08021e-05
prediction <- predict(fit, data_4pred)
pl <- plot(prediction)
ggplotly(pl) # OK

pl <- pl + geom_vline(aes(xintercept =4), linetype = "longdash")
ggplotly(pl) # error
```
```
Error in `tidyr::pivot_longer()`:
! Names must be unique.
✖ These names are duplicated:
  * "variable" at locations 4 and 13.
ℹ Use argument `names_repair` to specify repair strategy.
```

The "variable" column is used in {rbioacc} for the facet_wrap of the plots, in case of metabolites. It seems that in {plotly}, it is added to plot data when dealing with abline, vline and hline layers. (see internal function `to_basic` in `layers2traces.R` file)

I tried changing the column names of the plots generated from rbioacc and it fixed the issue. Should we change the naming convention in {rbioacc} to something a bit more specific?

**Comment by virgile-baudrot** [comment]
Thank you @milena-kaag for rising the issue.
We recently moved the repository of the package [here](https://gitlab.com/qonfluens/model/rbioacc/)
and therfore I moved your issue here: https://gitlab.com/qonfluens/model/rbioacc/-/issues/1
I'll attend to manage the issue in the coming weeks.
Best,
Virgile
